from pathlib import Path
p=Path('/home/ubuntu/Orbitpress/app/src/main/assets/index.html')
s=p.read_text()
css='''
/* OrbitPress polish: preserve the original visual language while improving touch targets and responsive layout. */
.orbit-tools-card{background:linear-gradient(135deg,#102c3b,#174957);color:#f4fffc;border:1px solid rgba(182,241,223,.22)}
.orbit-tools-card h2,.orbit-tools-card p{color:inherit}.orbit-tool-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.orbit-tool-grid .button{min-height:48px}
.orbit-trend-row,.pinflux-row{display:grid;grid-template-columns:1.2fr 1fr 1fr auto;gap:12px;align-items:end;padding:14px 0;border-bottom:1px solid var(--border,#dce7e5)}
.orbit-chip{display:inline-flex;align-items:center;border-radius:999px;padding:6px 10px;background:#e4f7f0;color:#164c42;font-size:.78rem;font-weight:700}
.orbit-empty{padding:20px;border:1px dashed var(--border,#dce7e5);border-radius:14px;color:var(--muted,#64748b)}
@media (max-width:760px){.orbit-tool-grid{grid-template-columns:1fr}.orbit-trend-row,.pinflux-row{grid-template-columns:1fr}.orbit-trend-row .button,.pinflux-row .button{width:100%}.screen{padding-inline:14px}.card{border-radius:18px}.button,.small-button,input,select,textarea{min-height:46px}.section-head{align-items:flex-start;gap:12px;flex-direction:column}}
'''
if '/* OrbitPress polish:' not in s:
    s=s.replace('</style>',css+'</style>',1)
card='''<section class="card orbit-tools-card"><div class="section-head"><div><p class="eyebrow" style="color:#b6f1df">OrbitPress Growth</p><h2>Content intelligence</h2><p>Use Pinterest Trends and PinFlux Save / Repin without replacing the existing publishing flow.</p></div><span class="tag">New</span></div><div class="orbit-tool-grid"><button class="button" type="button" onclick="showScreen('trends')">Pinterest Trends</button><button class="button" type="button" onclick="showScreen('pinflux')">PinFlux Save / Repin</button></div></section>'''
if 'id="orbit-growth-tools"' not in s:
    card=card.replace('<section class="card orbit-tools-card"','<section id="orbit-growth-tools" class="card orbit-tools-card"')
    anchor='<section class="screen" id="screen-pinterest">'
    s=s.replace(anchor,card+'\n    '+anchor,1)
trends='''<section class="screen" id="screen-trends"><p class="eyebrow">Pinterest Trends</p><h1>Find demand before you write.</h1><p class="screen-intro">Search the official Pinterest Trends source and turn related phrases into briefs, titles, Pin copy, and image prompts.</p><section class="card"><div class="pinterest-url-row"><div><label for="trendQuery">Keyword or niche</label><input id="trendQuery" placeholder="e.g. small kitchen ideas" autocomplete="off"></div><button id="readTrends" class="button" type="button">Read Trends</button></div><p class="helper">Source: <a href="https://trends.pinterest.com/" target="_blank" rel="noopener">trends.pinterest.com</a>. Results are kept in the local workspace.</p></section><section class="card"><div class="section-head"><div><h2>Related searches</h2><p id="trendStatus">No trend query yet.</p></div><button id="saveTrendKeyword" class="small-button" type="button" disabled>Save keyword</button></div><div id="trendResults" class="orbit-empty">Enter a keyword to see normalized trend results.</div></section><button class="button secondary" type="button" onclick="showScreen('pinterest')">Back to Pinterest</button></section>'''
pinflux='''<section class="screen" id="screen-pinflux"><p class="eyebrow">Pinterest PinFlux</p><h1>Save / Repin in controlled levels.</h1><p class="screen-intro">The original Pin stays the source. Each enabled account saves it to its assigned board; duplicate operations are excluded.</p><section class="card"><div class="row two"><div><label for="pinfluxSource">Source Pin ID</label><input id="pinfluxSource" placeholder="1234567890"></div><div><label for="pinfluxGroup">Group name</label><input id="pinfluxGroup" placeholder="Group 1"></div></div><div class="row three"><div><label for="pinfluxAccount">Account ID</label><input id="pinfluxAccount" placeholder="account-1"></div><div><label for="pinfluxBoard">Board ID</label><input id="pinfluxBoard" placeholder="board-1"></div><div><label for="pinfluxDelay">Delay seconds</label><input id="pinfluxDelay" type="number" min="5" value="30"></div></div><div class="orbit-tool-grid"><button id="addPinfluxAccount" class="button secondary" type="button">Add account</button><button id="planPinflux" class="button" type="button">Build Save / Repin plan</button></div></section><section class="card"><div class="section-head"><div><h2>Hierarchy and operations</h2><p id="pinfluxStatus">No plan built yet.</p></div><span class="orbit-chip">Save / Repin</span></div><div id="pinfluxResults" class="orbit-empty">Add accounts, then build a plan. The same Pin/account/board key will never be scheduled twice.</div></section><button class="button secondary" type="button" onclick="showScreen('pinterest')">Back to Pinterest</button></section>'''
if 'id="screen-trends"' not in s:
    s=s.replace('</main>',trends+'\n'+pinflux+'\n</main>',1)
js='''
    const orbitPinfluxAccounts=[];
    function orbitCall(type,payload,done){const id='orbit-'+Date.now();window.__nativeResult=window.__nativeResult||function(){};const old=window.__nativeResult;window.__nativeResult=function(resultId,raw){if(resultId===id){window.__nativeResult=old;done(JSON.parse(raw))}else old(resultId,raw)};bridge.call(JSON.stringify({id,type,...payload}))}
    function renderOrbitTrends(items){const host=$('trendResults');if(!items?.length){host.className='orbit-empty';host.textContent='No normalized trend rows were returned.';return}host.className='';host.innerHTML=items.map((x,i)=>`<div class="orbit-trend-row"><div><strong>${escapeHtml(x.keyword)}</strong><br><span class="helper">${escapeHtml(x.period||'30d')}</span></div><span class="orbit-chip">${escapeHtml(x.trend||'unknown')}</span><span>${Number(x.score||0).toFixed(1)} relevance</span><button class="small-button" type="button" onclick="navigator.clipboard?.writeText(${JSON.stringify(x.keyword)});notice('Keyword copied','good')">Copy</button></div>`).join('')}
    function readOrbitTrends(){const query=$('trendQuery').value.trim();if(!query)return notice('Enter a keyword first.','bad');$('readTrends').disabled=true;orbitCall('pinterestTrends',{query,results:[]},result=>{ $('readTrends').disabled=false;$('trendStatus').textContent=result.ok?'Official source ready; add visible results from the connected browser scan.':(result.message||'Trend request failed.');renderOrbitTrends(result.results||[]);$('saveTrendKeyword').disabled=!result.results?.length})}
    function addPinfluxAccount(){const a={id:$('pinfluxAccount').value.trim(),name:$('pinfluxAccount').value.trim(),boardId:$('pinfluxBoard').value.trim(),groupId:$('pinfluxGroup').value.trim()||'group-1',enabled:true};if(!a.id||!a.boardId)return notice('Account ID and Board ID are required.','bad');orbitPinfluxAccounts.push(a);$('pinfluxStatus').textContent=`${orbitPinfluxAccounts.length} account(s) staged locally.`}
    function planPinflux(){const source=$('pinfluxSource').value.trim();const group=$('pinfluxGroup').value.trim()||'group-1';orbitCall('pinfluxPlan',{sourcePinId:source,groups:[{id:group,name:group,parentId:'',delaySeconds:Number($('pinfluxDelay').value||30),maxOperations:20,enabled:true}],accounts:orbitPinfluxAccounts,completed:[]},result=>{if(!result.ok)return notice((result.errors||[]).join(' '),'bad');$('pinfluxStatus').textContent=`${result.operations.length} Save / Repin operation(s) planned.`;$('pinfluxResults').className='';$('pinfluxResults').innerHTML=result.operations.map((x,i)=>`<div class="pinflux-row"><div><strong>Level ${i+1}</strong><br>${escapeHtml(x.accountId)}</div><span>${escapeHtml(x.boardId)}</span><span>${x.delaySeconds}s delay</span><span class="orbit-chip">${x.action}</span></div>`).join('')||'No new operations.'})}
'''
if 'const orbitPinfluxAccounts' not in s:
    s=s.replace('    function initialize(){',js+'    function initialize(){',1)
    s=s.replace("$('menuRefresh').onclick=syncWordPress;", "$('menuRefresh').onclick=syncWordPress;$('readTrends').onclick=readOrbitTrends;$('addPinfluxAccount').onclick=addPinfluxAccount;$('planPinflux').onclick=planPinflux;")
p.write_text(s)
