from pathlib import Path
import re
p=Path('/home/ubuntu/Orbitpress/server/public/app/pinflux.js')
s=p.read_text()
s,n=re.subn(r"async function load\(\)\{.*?\n  async function sessionStatus", """async function load(){try{const data=await api('/pinflux/state');Object.assign(state,{...data,groups:(data.groups||[]).map((g,i)=>({...g,id:g.id||`group-${i+1}`})),accounts:data.accounts||[],completed:data.completed||[]});const sessions=await api('/pinflux/sessions');(sessions.accounts||[]).forEach(session=>{const account=accountById(session.accountId);if(account)account.connected=!!session.connected});render();for(const account of state.accounts.filter(a=>a.enabled!==false&&a.connected&&!a.boardsLoaded)){await loadBoards(account.id)}}catch(error){notice(error.message,'bad')}}
  async function sessionStatus""",s,count=1)
assert n==1,n
s,n=re.subn(r"async function loadBoards\(id\)\{.*?\n  async function addAccount", """async function loadBoards(id){const account=accountById(id);if(!account)return;try{const result=await api(`/pinflux/accounts/${encodeURIComponent(id)}/boards`);account.boards=result.boards||[];account.boardsLoaded=true;account.pinterestUsername=result.username||'';if(!account.boardId&&account.boards[0])account.boardId=account.boards[0].id||account.boards[0].boardId||account.boards[0].url||'';await save();render();notice(`${account.boards.length} لوحة تم استخراجها للحساب ${account.name}. تم اختيار أول لوحة تلقائيًا ويمكن تغييرها.`,'good')}catch(error){notice(`تعذر استخراج اللوحات: ${error.message}`,'bad')}}
  async function addAccount""",s,count=1)
assert n==1,n
s=s.replace("state.groups.push({id,name,parentId:$('pinfluxParentGroup').value.trim()||null", "if(state.groups.some(g=>g.id===id))return notice('معرّف المجموعة موجود مسبقًا.','bad');state.groups.push({id,name,parentId:$('pinfluxParentGroup').value.trim()||null",1)
s,n=re.subn(r"async function plan\(\)\{.*?\n  function mount", """async function plan(){state.sourcePinId=$('pinfluxSourcePin').value.trim();if(!state.sourcePinId)return notice('اختر Pin منشورًا من الحساب الرئيسي أولاً.','bad');try{await save();const data=await api('/pinflux/plan',{method:'POST',body:JSON.stringify({sourcePinId:state.sourcePinId,groups:state.groups,accounts:state.accounts,completed:state.completed})});const eligible=state.accounts.filter(a=>a.enabled!==false&&a.connected&&a.boardId&&state.groups.some(g=>g.id===a.groupId));$('pinfluxStatus').textContent=data.errors?.length?data.errors.join(' '):`${data.operations.length} عملية Save / Repin جاهزة. الحسابات المؤهلة: ${eligible.length} من ${state.accounts.length}.`;$('pinfluxOperations').innerHTML=data.operations.length?data.operations.map((x,i)=>`<div class=\\"pinflux-plan\\"><div><strong>Level ${i+1} · ${esc(x.accountName||x.accountId)}</strong><small>Group: ${esc(x.groupId)}</small></div><span>${esc(x.boardId)}</span><span>${x.delaySeconds}s</span><span class=\\"pinflux-pill\\">Save / Repin</span></div>`).join(''):`<div class=\\"pinflux-empty\\">لا توجد عمليات جديدة. تحقق من أن الحساب متصل، مفعّل، مرتبط بمجموعة، وتم اختيار لوحة له. الحسابات المؤهلة الآن: ${eligible.length} من ${state.accounts.length}.</div>`}catch(error){notice(error.message,'bad')}}
  function mount""",s,count=1)
assert n==1,n
p.write_text(s)
