from pathlib import Path
import re

p = Path('/home/ubuntu/Orbitpress/app/src/main/assets/index.html')
s = p.read_text()
old = re.search(r'    async function generateDraftImage\(draftId,kind\)\{.*?\n    async function generateAdditionalDraftImages\(draftId\)\{.*?\n', s, re.S)
if not old:
    raise SystemExit('image generation functions not found')
new = '''    function naturalPhotoPrompt(subject,keyword,context,aspect,role){const isFood=/food|recipe|kitchen|cook|bake|dish|meal|soup|bread|pasta|chicken|cake/i.test(`${subject} ${keyword} ${context}`);const vessel=isFood?' If food is shown, present it in a believable everyday serving vessel appropriate to the dish, with natural portions and subtle browned or imperfect edges where relevant.':'';return `Amateur editorial photograph taken with a premium smartphone camera, natural close-up of ${subject}, clearly showing ${keyword||subject}${role?`, ${role}`:''}. Real-life user-generated photography with authentic imperfect details, natural perspective, soft available light, realistic materials and textures, balanced composition, sharp focal subject, gentle background depth, ${context||'useful practical context'}, ${aspect}.${vessel} No text, no words, no letters, no numbers, no logos, no watermark, no collage, no artificial product render, no studio-perfect CGI.`}
    async function generateDraftImage(draftId,kind){const draft=getDraft(draftId);if(!draft)return;const button=$(kind==='pinterest'?'generatePinterest':'generateFeatured');if(button)button.disabled=true;try{const subject=draft.title||`${nicheLabel(draft.niche||'food')} article`;const keyword=draft.keyword||subject;const configured=kind==='pinterest'?(state.settingsSummary?.pinterestPrompt||''):(state.settingsSummary?.imagePrompt||'');const fallback=naturalPhotoPrompt(subject,keyword,`${nicheLabel(draft.niche||'food')} editorial content`,kind==='pinterest'?'portrait 2:3 vertical Pinterest composition':'landscape editorial composition','a strong single focal subject with clean negative space');const prompt=(configured||fallback).replaceAll('{{title}}',subject).replaceAll('{{keyword}}',keyword);const result=await nativeCall('generateImage',{kind,prompt,title:subject,keyword});draft.images=draft.images||{};draft.images[kind]=result.reference;persist();addLog('image_generated',`${kind} image generated for ${draft.title}`,{articleId:draft.id,wordpressStatus:'image_ready'});renderReview();notice(`${kind==='pinterest'?'Pinterest':'Featured'} image generated and saved locally.`,'good')}catch(error){notice(error.message||'Image generation failed.','bad')}finally{if(button)button.disabled=false}}
    async function generateAdditionalDraftImages(draftId){const draft=getDraft(draftId);const count=Math.max(0,Math.min(8,Number(state.settingsSummary?.articleImageCount||0)));if(!draft||!count)return;const button=$('generateAdditionalImages');if(button)button.disabled=true;try{draft.images=draft.images||{};draft.images.additional=[];for(let i=0;i<count;i++){const subject=draft.title||`${nicheLabel(draft.niche||'food')} article`;const keyword=draft.keyword||subject;const configured=state.settingsSummary?.imagePrompt||'';const roles=articleImageRoles(draft);const role=roles[i%roles.length];const fallback=naturalPhotoPrompt(subject,keyword,`${nicheLabel(draft.niche||'food')} article image`,'landscape editorial composition',role?.shot||'a distinct supporting moment that adds useful visual information');const prompt=(configured||fallback).replaceAll('{{title}}',subject).replaceAll('{{keyword}}',keyword).replaceAll('{{role}}',role?.shot||'supporting editorial moment');const result=await nativeCall('generateImage',{kind:'article',prompt,title:subject,keyword});draft.images.additional.push(result.reference)}persist();renderReview();notice(`${count} additional article images generated.`,'good')}catch(error){notice(error.message||'Additional image generation failed.','bad')}finally{if(button)button.disabled=false}}
'''
s = s[:old.start()] + new + s[old.end():]
p.write_text(s)

p = Path('/home/ubuntu/Orbitpress/server/public/index.html')
s = p.read_text()
s = s.replace('placeholder="Editorial food photography for {{title}}, no text..."', 'placeholder="Natural amateur editorial photograph with premium smartphone detail for {{title}}, no text..."')
s = s.replace('placeholder="Vertical 2:3 Pinterest image for {{title}}, no text..."', 'placeholder="Natural amateur vertical Pinterest photograph for {{title}}, realistic detail, no text..."')
p.write_text(s)
